// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.bsky.feed.getFeedSkeleton
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};
use crate::app_bsky::feed::SkeletonFeedPost;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetFeedSkeleton<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub feed: AtUri<S>,
    /// Defaults to `50`. Min: 1. Max: 100.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetFeedSkeletonOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub feed: Vec<SkeletonFeedPost<S>>,
    ///Unique identifier per request that may be passed back alongside interactions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub req_id: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum GetFeedSkeletonError {
    #[serde(rename = "UnknownFeed")]
    UnknownFeed(Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other { error: SmolStr, message: Option<SmolStr> },
}

impl core::fmt::Display for GetFeedSkeletonError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::UnknownFeed(msg) => {
                write!(f, "UnknownFeed")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `app.bsky.feed.getFeedSkeleton` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetFeedSkeletonOutput<S>` for this endpoint.*/
pub struct GetFeedSkeletonResponse;
impl jacquard_common::xrpc::XrpcResp for GetFeedSkeletonResponse {
    const NSID: &'static str = "app.bsky.feed.getFeedSkeleton";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetFeedSkeletonOutput<S>;
    type Err = GetFeedSkeletonError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetFeedSkeleton<S> {
    const NSID: &'static str = "app.bsky.feed.getFeedSkeleton";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetFeedSkeletonResponse;
}

/** Endpoint marker for the `app.bsky.feed.getFeedSkeleton` query.

Path: `/xrpc/app.bsky.feed.getFeedSkeleton`. The request payload type is `GetFeedSkeleton<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetFeedSkeletonRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetFeedSkeletonRequest {
    const PATH: &'static str = "/xrpc/app.bsky.feed.getFeedSkeleton";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetFeedSkeleton<S>;
    type Response = GetFeedSkeletonResponse;
}

fn _default_limit() -> Option<i64> {
    Some(50i64)
}

pub mod get_feed_skeleton_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Feed;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Feed = Unset;
    }
    ///State transition - sets the `feed` field to Set
    pub struct SetFeed<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetFeed<St> {}
    impl<St: State> State for SetFeed<St> {
        type Feed = Set<members::feed>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `feed` field
        pub struct feed(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetFeedSkeletonBuilder<
    St: get_feed_skeleton_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<AtUri<S>>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl GetFeedSkeleton<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetFeedSkeletonBuilder<get_feed_skeleton_state::Empty, DefaultStr> {
        GetFeedSkeletonBuilder::new()
    }
}

impl<S: BosStr> GetFeedSkeleton<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetFeedSkeletonBuilder<get_feed_skeleton_state::Empty, S> {
        GetFeedSkeletonBuilder::builder()
    }
}

impl GetFeedSkeletonBuilder<get_feed_skeleton_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetFeedSkeletonBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetFeedSkeletonBuilder<get_feed_skeleton_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetFeedSkeletonBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: get_feed_skeleton_state::State, S: BosStr> GetFeedSkeletonBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> GetFeedSkeletonBuilder<St, S>
where
    St: get_feed_skeleton_state::State,
    St::Feed: get_feed_skeleton_state::IsUnset,
{
    /// Set the `feed` field (required)
    pub fn feed(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> GetFeedSkeletonBuilder<get_feed_skeleton_state::SetFeed<St>, S> {
        self._fields.1 = Option::Some(value.into());
        GetFeedSkeletonBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: get_feed_skeleton_state::State, S: BosStr> GetFeedSkeletonBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> GetFeedSkeletonBuilder<St, S>
where
    St: get_feed_skeleton_state::State,
    St::Feed: get_feed_skeleton_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetFeedSkeleton<S> {
        GetFeedSkeleton {
            cursor: self._fields.0,
            feed: self._fields.1.unwrap(),
            limit: self._fields.2,
        }
    }
}