// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.bsky.feed.getPosts
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::app_bsky::feed::PostView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetPosts<S: BosStr = DefaultStr> {
    pub uris: Vec<AtUri<S>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetPostsOutput<S: BosStr = DefaultStr> {
    pub posts: Vec<PostView<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.bsky.feed.getPosts` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetPostsOutput<S>` for this endpoint.*/
pub struct GetPostsResponse;
impl jacquard_common::xrpc::XrpcResp for GetPostsResponse {
    const NSID: &'static str = "app.bsky.feed.getPosts";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetPostsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetPosts<S> {
    const NSID: &'static str = "app.bsky.feed.getPosts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetPostsResponse;
}

/** Endpoint marker for the `app.bsky.feed.getPosts` query.

Path: `/xrpc/app.bsky.feed.getPosts`. The request payload type is `GetPosts<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetPostsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetPostsRequest {
    const PATH: &'static str = "/xrpc/app.bsky.feed.getPosts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetPosts<S>;
    type Response = GetPostsResponse;
}

pub mod get_posts_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uris;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uris = Unset;
    }
    ///State transition - sets the `uris` field to Set
    pub struct SetUris<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUris<St> {}
    impl<St: State> State for SetUris<St> {
        type Uris = Set<members::uris>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uris` field
        pub struct uris(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetPostsBuilder<St: get_posts_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Vec<AtUri<S>>>,),
    _type: PhantomData<fn() -> S>,
}

impl GetPosts<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetPostsBuilder<get_posts_state::Empty, DefaultStr> {
        GetPostsBuilder::new()
    }
}

impl<S: BosStr> GetPosts<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetPostsBuilder<get_posts_state::Empty, S> {
        GetPostsBuilder::builder()
    }
}

impl GetPostsBuilder<get_posts_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetPostsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetPostsBuilder<get_posts_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetPostsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetPostsBuilder<St, S>
where
    St: get_posts_state::State,
    St::Uris: get_posts_state::IsUnset,
{
    /// Set the `uris` field (required)
    pub fn uris(
        mut self,
        value: impl Into<Vec<AtUri<S>>>,
    ) -> GetPostsBuilder<get_posts_state::SetUris<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetPostsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetPostsBuilder<St, S>
where
    St: get_posts_state::State,
    St::Uris: get_posts_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetPosts<S> {
        GetPosts {
            uris: self._fields.0.unwrap(),
        }
    }
}