// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.bsky.feed.getRepostedBy
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{AtUri, Cid};
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::app_bsky::actor::ProfileView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetRepostedBy<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    ///Defaults to `50`. Min: 1. Max: 100.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    pub uri: AtUri<S>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetRepostedByOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub reposted_by: Vec<ProfileView<S>>,
    pub uri: AtUri<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Response type for app.bsky.feed.getRepostedBy
pub struct GetRepostedByResponse;
impl jacquard_common::xrpc::XrpcResp for GetRepostedByResponse {
    const NSID: &'static str = "app.bsky.feed.getRepostedBy";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetRepostedByOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetRepostedBy<S> {
    const NSID: &'static str = "app.bsky.feed.getRepostedBy";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetRepostedByResponse;
}

/// Endpoint type for app.bsky.feed.getRepostedBy
pub struct GetRepostedByRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetRepostedByRequest {
    const PATH: &'static str = "/xrpc/app.bsky.feed.getRepostedBy";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetRepostedBy<S>;
    type Response = GetRepostedByResponse;
}

fn _default_limit() -> Option<i64> {
    Some(50i64)
}

pub mod get_reposted_by_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uri;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uri = Unset;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUri<St> {}
    impl<St: State> State for SetUri<St> {
        type Uri = Set<members::uri>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uri` field
        pub struct uri(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetRepostedByBuilder<S: BosStr, St: get_reposted_by_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Cid<S>>, Option<S>, Option<i64>, Option<AtUri<S>>),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> GetRepostedBy<S> {
    /// Create a new builder for this type.
    pub fn new() -> GetRepostedByBuilder<S, get_reposted_by_state::Empty> {
        GetRepostedByBuilder::new()
    }
}

impl<S: BosStr> GetRepostedByBuilder<S, get_reposted_by_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        GetRepostedByBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: get_reposted_by_state::State> GetRepostedByBuilder<S, St> {
    /// Set the `cid` field (optional)
    pub fn cid(mut self, value: impl Into<Option<Cid<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cid` field to an Option value (optional)
    pub fn maybe_cid(mut self, value: Option<Cid<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<S: BosStr, St: get_reposted_by_state::State> GetRepostedByBuilder<S, St> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<S: BosStr, St: get_reposted_by_state::State> GetRepostedByBuilder<S, St> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<S: BosStr, St> GetRepostedByBuilder<S, St>
where
    St: get_reposted_by_state::State,
    St::Uri: get_reposted_by_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> GetRepostedByBuilder<S, get_reposted_by_state::SetUri<St>> {
        self._fields.3 = Option::Some(value.into());
        GetRepostedByBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> GetRepostedByBuilder<S, St>
where
    St: get_reposted_by_state::State,
    St::Uri: get_reposted_by_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetRepostedBy<S> {
        GetRepostedBy {
            cid: self._fields.0,
            cursor: self._fields.1,
            limit: self._fields.2,
            uri: self._fields.3.unwrap(),
        }
    }
}