// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: chat.bsky.moderation.getMessageContext
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};
use crate::chat_bsky::convo::MessageView;
use crate::chat_bsky::convo::SystemMessageView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetMessageContext<S: BosStr = DefaultStr> {
    ///Defaults to `5`.
    #[serde(default = "_default_after")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub after: Option<i64>,
    ///Defaults to `5`.
    #[serde(default = "_default_before")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub before: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub convo_id: Option<S>,
    ///Defaults to `10`. Min: 0. Max: 1000.
    #[serde(default = "_default_max_interleaved_system_messages")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_interleaved_system_messages: Option<i64>,
    pub message_id: S,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetMessageContextOutput<S: BosStr = DefaultStr> {
    pub messages: Vec<GetMessageContextOutputMessagesItem<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[open_union]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(tag = "$type", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub enum GetMessageContextOutputMessagesItem<S: BosStr = DefaultStr> {
    #[serde(rename = "chat.bsky.convo.defs#messageView")]
    MessageView(Box<MessageView<S>>),
    #[serde(rename = "chat.bsky.convo.defs#systemMessageView")]
    SystemMessageView(Box<SystemMessageView<S>>),
}

/// Response type for chat.bsky.moderation.getMessageContext
pub struct GetMessageContextResponse;
impl jacquard_common::xrpc::XrpcResp for GetMessageContextResponse {
    const NSID: &'static str = "chat.bsky.moderation.getMessageContext";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetMessageContextOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetMessageContext<S> {
    const NSID: &'static str = "chat.bsky.moderation.getMessageContext";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetMessageContextResponse;
}

/// Endpoint type for chat.bsky.moderation.getMessageContext
pub struct GetMessageContextRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetMessageContextRequest {
    const PATH: &'static str = "/xrpc/chat.bsky.moderation.getMessageContext";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetMessageContext<S>;
    type Response = GetMessageContextResponse;
}

fn _default_after() -> Option<i64> {
    Some(5i64)
}

fn _default_before() -> Option<i64> {
    Some(5i64)
}

fn _default_max_interleaved_system_messages() -> Option<i64> {
    Some(10i64)
}

pub mod get_message_context_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type MessageId;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type MessageId = Unset;
    }
    ///State transition - sets the `message_id` field to Set
    pub struct SetMessageId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetMessageId<St> {}
    impl<St: State> State for SetMessageId<St> {
        type MessageId = Set<members::message_id>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `message_id` field
        pub struct message_id(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetMessageContextBuilder<S: BosStr, St: get_message_context_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<i64>, Option<S>, Option<i64>, Option<S>),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> GetMessageContext<S> {
    /// Create a new builder for this type.
    pub fn new() -> GetMessageContextBuilder<S, get_message_context_state::Empty> {
        GetMessageContextBuilder::new()
    }
}

impl<S: BosStr> GetMessageContextBuilder<S, get_message_context_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        GetMessageContextBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: get_message_context_state::State> GetMessageContextBuilder<S, St> {
    /// Set the `after` field (optional)
    pub fn after(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `after` field to an Option value (optional)
    pub fn maybe_after(mut self, value: Option<i64>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<S: BosStr, St: get_message_context_state::State> GetMessageContextBuilder<S, St> {
    /// Set the `before` field (optional)
    pub fn before(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `before` field to an Option value (optional)
    pub fn maybe_before(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<S: BosStr, St: get_message_context_state::State> GetMessageContextBuilder<S, St> {
    /// Set the `convoId` field (optional)
    pub fn convo_id(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `convoId` field to an Option value (optional)
    pub fn maybe_convo_id(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<S: BosStr, St: get_message_context_state::State> GetMessageContextBuilder<S, St> {
    /// Set the `maxInterleavedSystemMessages` field (optional)
    pub fn max_interleaved_system_messages(
        mut self,
        value: impl Into<Option<i64>>,
    ) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `maxInterleavedSystemMessages` field to an Option value (optional)
    pub fn maybe_max_interleaved_system_messages(mut self, value: Option<i64>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<S: BosStr, St> GetMessageContextBuilder<S, St>
where
    St: get_message_context_state::State,
    St::MessageId: get_message_context_state::IsUnset,
{
    /// Set the `messageId` field (required)
    pub fn message_id(
        mut self,
        value: impl Into<S>,
    ) -> GetMessageContextBuilder<S, get_message_context_state::SetMessageId<St>> {
        self._fields.4 = Option::Some(value.into());
        GetMessageContextBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> GetMessageContextBuilder<S, St>
where
    St: get_message_context_state::State,
    St::MessageId: get_message_context_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetMessageContext<S> {
        GetMessageContext {
            after: self._fields.0,
            before: self._fields.1,
            convo_id: self._fields.2,
            max_interleaved_system_messages: self._fields.3,
            message_id: self._fields.4.unwrap(),
        }
    }
}