// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.identity.requestPlcOperationSignature
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
/** Request marker for the `com.atproto.identity.requestPlcOperationSignature` procedure.

This endpoint has no request parameters or input body; send this marker with `jacquard::Client`.*/

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct RequestPlcOperationSignature;
/** Response marker for the `com.atproto.identity.requestPlcOperationSignature` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `()` for this endpoint.*/
pub struct RequestPlcOperationSignatureResponse;
impl jacquard_common::xrpc::XrpcResp for RequestPlcOperationSignatureResponse {
    const NSID: &'static str = "com.atproto.identity.requestPlcOperationSignature";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ();
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for RequestPlcOperationSignature {
    const NSID: &'static str = "com.atproto.identity.requestPlcOperationSignature";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RequestPlcOperationSignatureResponse;
}

/** Endpoint marker for the `com.atproto.identity.requestPlcOperationSignature` procedure.

Path: `/xrpc/com.atproto.identity.requestPlcOperationSignature`. The request payload type is `RequestPlcOperationSignature`; use this marker with lower-level `XrpcEndpoint` APIs when you need endpoint metadata.*/
pub struct RequestPlcOperationSignatureRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RequestPlcOperationSignatureRequest {
    const PATH: &'static str = "/xrpc/com.atproto.identity.requestPlcOperationSignature";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = RequestPlcOperationSignature;
    type Response = RequestPlcOperationSignatureResponse;
}