// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.identity.resolveDid
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Did;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ResolveDid<S: BosStr = DefaultStr> {
    pub did: Did<S>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ResolveDidOutput<S: BosStr = DefaultStr> {
    ///The complete DID document for the identity.
    pub did_doc: Data<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum ResolveDidError {
    /// The DID resolution process confirmed that there is no current DID.
    #[serde(rename = "DidNotFound")]
    DidNotFound(Option<SmolStr>),
    /// The DID previously existed, but has been deactivated.
    #[serde(rename = "DidDeactivated")]
    DidDeactivated(Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other { error: SmolStr, message: Option<SmolStr> },
}

impl core::fmt::Display for ResolveDidError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::DidNotFound(msg) => {
                write!(f, "DidNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::DidDeactivated(msg) => {
                write!(f, "DidDeactivated")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `com.atproto.identity.resolveDid` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `ResolveDidOutput<S>` for this endpoint.*/
pub struct ResolveDidResponse;
impl jacquard_common::xrpc::XrpcResp for ResolveDidResponse {
    const NSID: &'static str = "com.atproto.identity.resolveDid";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ResolveDidOutput<S>;
    type Err = ResolveDidError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for ResolveDid<S> {
    const NSID: &'static str = "com.atproto.identity.resolveDid";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ResolveDidResponse;
}

/** Endpoint marker for the `com.atproto.identity.resolveDid` query.

Path: `/xrpc/com.atproto.identity.resolveDid`. The request payload type is `ResolveDid<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct ResolveDidRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ResolveDidRequest {
    const PATH: &'static str = "/xrpc/com.atproto.identity.resolveDid";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = ResolveDid<S>;
    type Response = ResolveDidResponse;
}

pub mod resolve_did_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDid<St> {}
    impl<St: State> State for SetDid<St> {
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ResolveDidBuilder<St: resolve_did_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Did<S>>,),
    _type: PhantomData<fn() -> S>,
}

impl ResolveDid<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ResolveDidBuilder<resolve_did_state::Empty, DefaultStr> {
        ResolveDidBuilder::new()
    }
}

impl<S: BosStr> ResolveDid<S> {
    /// Create a new builder for this type
    pub fn builder() -> ResolveDidBuilder<resolve_did_state::Empty, S> {
        ResolveDidBuilder::builder()
    }
}

impl ResolveDidBuilder<resolve_did_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ResolveDidBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ResolveDidBuilder<resolve_did_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ResolveDidBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ResolveDidBuilder<St, S>
where
    St: resolve_did_state::State,
    St::Did: resolve_did_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<S>>,
    ) -> ResolveDidBuilder<resolve_did_state::SetDid<St>, S> {
        self._fields.0 = Option::Some(value.into());
        ResolveDidBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ResolveDidBuilder<St, S>
where
    St: resolve_did_state::State,
    St::Did: resolve_did_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> ResolveDid<S> {
        ResolveDid {
            did: self._fields.0.unwrap(),
        }
    }
}