// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `tools.ozone` Lexicon namespace/module.
pub mod communication;
pub mod hosting;
pub mod moderation;
pub mod queue;
pub mod report;
pub mod safelink;
pub mod server;
pub mod set;
pub mod setting;
pub mod signature;
pub mod team;
pub mod verification;