services:
  aqua-api:
    build:
      context: .
      dockerfile: apps/aqua/Dockerfile
    container_name: aqua-app
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - postgres
      - garnet
    env_file:
      - .env
  status-api:
    build:
      context: .
      dockerfile: apps/status/Dockerfile
    container_name: status-api
    ports:
      - "3002:3002"
    networks:
      - app_network
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://teal:awesomeness@postgres/teal
      STATUS_API_PORT: 3002
