version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass123
      POSTGRES_DB: teal_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test_network
    command: postgres -c log_statement=all -c log_destination=stderr

networks:
  test_network:
    driver: bridge

volumes:
  postgres_test_data:
