[build.env]
passthrough = [
    "CARGO_HOME",
    "CARGO_TARGET_DIR",
    "SQLX_OFFLINE",
    "PKG_CONFIG_ALLOW_CROSS",
]

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "CARGO_HOME",
    "CARGO_TARGET_DIR",
    "SQLX_OFFLINE",
    "PKG_CONFIG_ALLOW_CROSS",
]
