// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.bsky.unspecced.getSuggestedUsersSkeleton
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Did;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetSuggestedUsersSkeleton<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<S>,
    ///Defaults to `25`. Min: 1. Max: 50.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub viewer: Option<Did<S>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetSuggestedUsersSkeletonOutput<S: BosStr = DefaultStr> {
    pub dids: Vec<Did<S>>,
    ///DEPRECATED: use recIdStr instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rec_id: Option<S>,
    ///Snowflake for this recommendation, use when submitting recommendation events.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rec_id_str: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Response type for app.bsky.unspecced.getSuggestedUsersSkeleton
pub struct GetSuggestedUsersSkeletonResponse;
impl jacquard_common::xrpc::XrpcResp for GetSuggestedUsersSkeletonResponse {
    const NSID: &'static str = "app.bsky.unspecced.getSuggestedUsersSkeleton";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetSuggestedUsersSkeletonOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetSuggestedUsersSkeleton<S> {
    const NSID: &'static str = "app.bsky.unspecced.getSuggestedUsersSkeleton";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetSuggestedUsersSkeletonResponse;
}

/// Endpoint type for app.bsky.unspecced.getSuggestedUsersSkeleton
pub struct GetSuggestedUsersSkeletonRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetSuggestedUsersSkeletonRequest {
    const PATH: &'static str = "/xrpc/app.bsky.unspecced.getSuggestedUsersSkeleton";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetSuggestedUsersSkeleton<S>;
    type Response = GetSuggestedUsersSkeletonResponse;
}

fn _default_limit() -> Option<i64> {
    Some(25i64)
}

pub mod get_suggested_users_skeleton_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetSuggestedUsersSkeletonBuilder<
    S: BosStr,
    St: get_suggested_users_skeleton_state::State,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>, Option<Did<S>>),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> GetSuggestedUsersSkeleton<S> {
    /// Create a new builder for this type.
    pub fn new() -> GetSuggestedUsersSkeletonBuilder<
        S,
        get_suggested_users_skeleton_state::Empty,
    > {
        GetSuggestedUsersSkeletonBuilder::new()
    }
}

impl<
    S: BosStr,
> GetSuggestedUsersSkeletonBuilder<S, get_suggested_users_skeleton_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        GetSuggestedUsersSkeletonBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<
    S: BosStr,
    St: get_suggested_users_skeleton_state::State,
> GetSuggestedUsersSkeletonBuilder<S, St> {
    /// Set the `category` field (optional)
    pub fn category(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `category` field to an Option value (optional)
    pub fn maybe_category(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<
    S: BosStr,
    St: get_suggested_users_skeleton_state::State,
> GetSuggestedUsersSkeletonBuilder<S, St> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<
    S: BosStr,
    St: get_suggested_users_skeleton_state::State,
> GetSuggestedUsersSkeletonBuilder<S, St> {
    /// Set the `viewer` field (optional)
    pub fn viewer(mut self, value: impl Into<Option<Did<S>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `viewer` field to an Option value (optional)
    pub fn maybe_viewer(mut self, value: Option<Did<S>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<S: BosStr, St> GetSuggestedUsersSkeletonBuilder<S, St>
where
    St: get_suggested_users_skeleton_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetSuggestedUsersSkeleton<S> {
        GetSuggestedUsersSkeleton {
            category: self._fields.0,
            limit: self._fields.1,
            viewer: self._fields.2,
        }
    }
}