// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.bsky.graph.getListMutes
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::app_bsky::graph::ListView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetListMutes<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    /// Defaults to `50`. Min: 1. Max: 100.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetListMutesOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub lists: Vec<ListView<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.bsky.graph.getListMutes` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetListMutesOutput<S>` for this endpoint.*/
pub struct GetListMutesResponse;
impl jacquard_common::xrpc::XrpcResp for GetListMutesResponse {
    const NSID: &'static str = "app.bsky.graph.getListMutes";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetListMutesOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetListMutes<S> {
    const NSID: &'static str = "app.bsky.graph.getListMutes";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetListMutesResponse;
}

/** Endpoint marker for the `app.bsky.graph.getListMutes` query.

Path: `/xrpc/app.bsky.graph.getListMutes`. The request payload type is `GetListMutes<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetListMutesRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetListMutesRequest {
    const PATH: &'static str = "/xrpc/app.bsky.graph.getListMutes";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetListMutes<S>;
    type Response = GetListMutesResponse;
}

fn _default_limit() -> Option<i64> {
    Some(50i64)
}

pub mod get_list_mutes_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetListMutesBuilder<St: get_list_mutes_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl GetListMutes<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetListMutesBuilder<get_list_mutes_state::Empty, DefaultStr> {
        GetListMutesBuilder::new()
    }
}

impl<S: BosStr> GetListMutes<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetListMutesBuilder<get_list_mutes_state::Empty, S> {
        GetListMutesBuilder::builder()
    }
}

impl GetListMutesBuilder<get_list_mutes_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetListMutesBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetListMutesBuilder<get_list_mutes_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetListMutesBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St: get_list_mutes_state::State, S: BosStr> GetListMutesBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: get_list_mutes_state::State, S: BosStr> GetListMutesBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> GetListMutesBuilder<St, S>
where
    St: get_list_mutes_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetListMutes<S> {
        GetListMutes {
            cursor: self._fields.0,
            limit: self._fields.1,
        }
    }
}