// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.bsky.actor.searchActors
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::app_bsky::actor::ProfileView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct SearchActors<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    /// Defaults to `25`. Min: 1. Max: 100.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub term: Option<S>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct SearchActorsOutput<S: BosStr = DefaultStr> {
    pub actors: Vec<ProfileView<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `app.bsky.actor.searchActors` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `SearchActorsOutput<S>` for this endpoint.*/
pub struct SearchActorsResponse;
impl jacquard_common::xrpc::XrpcResp for SearchActorsResponse {
    const NSID: &'static str = "app.bsky.actor.searchActors";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = SearchActorsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for SearchActors<S> {
    const NSID: &'static str = "app.bsky.actor.searchActors";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = SearchActorsResponse;
}

/** Endpoint marker for the `app.bsky.actor.searchActors` query.

Path: `/xrpc/app.bsky.actor.searchActors`. The request payload type is `SearchActors<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct SearchActorsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for SearchActorsRequest {
    const PATH: &'static str = "/xrpc/app.bsky.actor.searchActors";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = SearchActors<S>;
    type Response = SearchActorsResponse;
}

fn _default_limit() -> Option<i64> {
    Some(25i64)
}

pub mod search_actors_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct SearchActorsBuilder<St: search_actors_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>, Option<S>, Option<S>),
    _type: PhantomData<fn() -> S>,
}

impl SearchActors<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> SearchActorsBuilder<search_actors_state::Empty, DefaultStr> {
        SearchActorsBuilder::new()
    }
}

impl<S: BosStr> SearchActors<S> {
    /// Create a new builder for this type
    pub fn builder() -> SearchActorsBuilder<search_actors_state::Empty, S> {
        SearchActorsBuilder::builder()
    }
}

impl SearchActorsBuilder<search_actors_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        SearchActorsBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> SearchActorsBuilder<search_actors_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        SearchActorsBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: search_actors_state::State, S: BosStr> SearchActorsBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: search_actors_state::State, S: BosStr> SearchActorsBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: search_actors_state::State, S: BosStr> SearchActorsBuilder<St, S> {
    /// Set the `q` field (optional)
    pub fn q(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `q` field to an Option value (optional)
    pub fn maybe_q(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: search_actors_state::State, S: BosStr> SearchActorsBuilder<St, S> {
    /// Set the `term` field (optional)
    pub fn term(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `term` field to an Option value (optional)
    pub fn maybe_term(mut self, value: Option<S>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St, S: BosStr> SearchActorsBuilder<St, S>
where
    St: search_actors_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> SearchActors<S> {
        SearchActors {
            cursor: self._fields.0,
            limit: self._fields.1,
            q: self._fields.2,
            term: self._fields.3,
        }
    }
}