// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.temp.requestPhoneVerification
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct RequestPhoneVerification<S: BosStr = DefaultStr> {
    pub phone_number: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `com.atproto.temp.requestPhoneVerification` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `()` for this endpoint.*/
pub struct RequestPhoneVerificationResponse;
impl jacquard_common::xrpc::XrpcResp for RequestPhoneVerificationResponse {
    const NSID: &'static str = "com.atproto.temp.requestPhoneVerification";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ();
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for RequestPhoneVerification<S> {
    const NSID: &'static str = "com.atproto.temp.requestPhoneVerification";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RequestPhoneVerificationResponse;
}

/** Endpoint marker for the `com.atproto.temp.requestPhoneVerification` procedure.

Path: `/xrpc/com.atproto.temp.requestPhoneVerification`. The request payload type is `RequestPhoneVerification<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct RequestPhoneVerificationRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RequestPhoneVerificationRequest {
    const PATH: &'static str = "/xrpc/com.atproto.temp.requestPhoneVerification";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = RequestPhoneVerification<S>;
    type Response = RequestPhoneVerificationResponse;
}