// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.sync.getHostStatus
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};
use crate::com_atproto::sync::HostStatus;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetHostStatus<S: BosStr = DefaultStr> {
    pub hostname: S,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetHostStatusOutput<S: BosStr = DefaultStr> {
    ///Number of accounts on the server which are associated with the upstream host. Note that the upstream may actually have more accounts.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_count: Option<i64>,
    pub hostname: S,
    ///Recent repo stream event sequence number. May be delayed from actual stream processing (eg, persisted cursor not in-memory cursor).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<HostStatus<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum GetHostStatusError {
    #[serde(rename = "HostNotFound")]
    HostNotFound(Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other { error: SmolStr, message: Option<SmolStr> },
}

impl core::fmt::Display for GetHostStatusError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::HostNotFound(msg) => {
                write!(f, "HostNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/// Response type for com.atproto.sync.getHostStatus
pub struct GetHostStatusResponse;
impl jacquard_common::xrpc::XrpcResp for GetHostStatusResponse {
    const NSID: &'static str = "com.atproto.sync.getHostStatus";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetHostStatusOutput<S>;
    type Err = GetHostStatusError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetHostStatus<S> {
    const NSID: &'static str = "com.atproto.sync.getHostStatus";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetHostStatusResponse;
}

/// Endpoint type for com.atproto.sync.getHostStatus
pub struct GetHostStatusRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetHostStatusRequest {
    const PATH: &'static str = "/xrpc/com.atproto.sync.getHostStatus";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetHostStatus<S>;
    type Response = GetHostStatusResponse;
}

pub mod get_host_status_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Hostname;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Hostname = Unset;
    }
    ///State transition - sets the `hostname` field to Set
    pub struct SetHostname<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetHostname<St> {}
    impl<St: State> State for SetHostname<St> {
        type Hostname = Set<members::hostname>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `hostname` field
        pub struct hostname(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetHostStatusBuilder<S: BosStr, St: get_host_status_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>,),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> GetHostStatus<S> {
    /// Create a new builder for this type.
    pub fn new() -> GetHostStatusBuilder<S, get_host_status_state::Empty> {
        GetHostStatusBuilder::new()
    }
}

impl<S: BosStr> GetHostStatusBuilder<S, get_host_status_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        GetHostStatusBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> GetHostStatusBuilder<S, St>
where
    St: get_host_status_state::State,
    St::Hostname: get_host_status_state::IsUnset,
{
    /// Set the `hostname` field (required)
    pub fn hostname(
        mut self,
        value: impl Into<S>,
    ) -> GetHostStatusBuilder<S, get_host_status_state::SetHostname<St>> {
        self._fields.0 = Option::Some(value.into());
        GetHostStatusBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> GetHostStatusBuilder<S, St>
where
    St: get_host_status_state::State,
    St::Hostname: get_host_status_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetHostStatus<S> {
        GetHostStatus {
            hostname: self._fields.0.unwrap(),
        }
    }
}