// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.sync.listBlobs
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Did, Tid, Cid};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ListBlobs<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub did: Did<S>,
    /// Defaults to `500`. Min: 1. Max: 1000.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub since: Option<Tid>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ListBlobsOutput<S: BosStr = DefaultStr> {
    pub cids: Vec<Cid<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum ListBlobsError {
    #[serde(rename = "RepoNotFound")]
    RepoNotFound(Option<SmolStr>),
    #[serde(rename = "RepoTakendown")]
    RepoTakendown(Option<SmolStr>),
    #[serde(rename = "RepoSuspended")]
    RepoSuspended(Option<SmolStr>),
    #[serde(rename = "RepoDeactivated")]
    RepoDeactivated(Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other { error: SmolStr, message: Option<SmolStr> },
}

impl core::fmt::Display for ListBlobsError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::RepoNotFound(msg) => {
                write!(f, "RepoNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::RepoTakendown(msg) => {
                write!(f, "RepoTakendown")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::RepoSuspended(msg) => {
                write!(f, "RepoSuspended")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::RepoDeactivated(msg) => {
                write!(f, "RepoDeactivated")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `com.atproto.sync.listBlobs` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `ListBlobsOutput<S>` for this endpoint.*/
pub struct ListBlobsResponse;
impl jacquard_common::xrpc::XrpcResp for ListBlobsResponse {
    const NSID: &'static str = "com.atproto.sync.listBlobs";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ListBlobsOutput<S>;
    type Err = ListBlobsError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for ListBlobs<S> {
    const NSID: &'static str = "com.atproto.sync.listBlobs";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ListBlobsResponse;
}

/** Endpoint marker for the `com.atproto.sync.listBlobs` query.

Path: `/xrpc/com.atproto.sync.listBlobs`. The request payload type is `ListBlobs<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct ListBlobsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ListBlobsRequest {
    const PATH: &'static str = "/xrpc/com.atproto.sync.listBlobs";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = ListBlobs<S>;
    type Response = ListBlobsResponse;
}

fn _default_limit() -> Option<i64> {
    Some(500i64)
}

pub mod list_blobs_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDid<St> {}
    impl<St: State> State for SetDid<St> {
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ListBlobsBuilder<St: list_blobs_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<Did<S>>, Option<i64>, Option<Tid>),
    _type: PhantomData<fn() -> S>,
}

impl ListBlobs<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ListBlobsBuilder<list_blobs_state::Empty, DefaultStr> {
        ListBlobsBuilder::new()
    }
}

impl<S: BosStr> ListBlobs<S> {
    /// Create a new builder for this type
    pub fn builder() -> ListBlobsBuilder<list_blobs_state::Empty, S> {
        ListBlobsBuilder::builder()
    }
}

impl ListBlobsBuilder<list_blobs_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ListBlobsBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ListBlobsBuilder<list_blobs_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ListBlobsBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: list_blobs_state::State, S: BosStr> ListBlobsBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> ListBlobsBuilder<St, S>
where
    St: list_blobs_state::State,
    St::Did: list_blobs_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<S>>,
    ) -> ListBlobsBuilder<list_blobs_state::SetDid<St>, S> {
        self._fields.1 = Option::Some(value.into());
        ListBlobsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: list_blobs_state::State, S: BosStr> ListBlobsBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: list_blobs_state::State, S: BosStr> ListBlobsBuilder<St, S> {
    /// Set the `since` field (optional)
    pub fn since(mut self, value: impl Into<Option<Tid>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `since` field to an Option value (optional)
    pub fn maybe_since(mut self, value: Option<Tid>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St, S: BosStr> ListBlobsBuilder<St, S>
where
    St: list_blobs_state::State,
    St::Did: list_blobs_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> ListBlobs<S> {
        ListBlobs {
            cursor: self._fields.0,
            did: self._fields.1.unwrap(),
            limit: self._fields.2,
            since: self._fields.3,
        }
    }
}