// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `com.atproto.temp` namespace.
pub mod add_reserved_handle;
pub mod check_signup_queue;
pub mod fetch_labels;
pub mod request_phone_verification;
