// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: chat.bsky.convo.listConvos
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::chat_bsky::convo::ConvoView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ListConvos<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<S>,
    /// Defaults to `50`. Min: 1. Max: 100.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lock_status: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub read_state: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<S>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ListConvosOutput<S: BosStr = DefaultStr> {
    pub convos: Vec<ConvoView<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `chat.bsky.convo.listConvos` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `ListConvosOutput<S>` for this endpoint.*/
pub struct ListConvosResponse;
impl jacquard_common::xrpc::XrpcResp for ListConvosResponse {
    const NSID: &'static str = "chat.bsky.convo.listConvos";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ListConvosOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for ListConvos<S> {
    const NSID: &'static str = "chat.bsky.convo.listConvos";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ListConvosResponse;
}

/** Endpoint marker for the `chat.bsky.convo.listConvos` query.

Path: `/xrpc/chat.bsky.convo.listConvos`. The request payload type is `ListConvos<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct ListConvosRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ListConvosRequest {
    const PATH: &'static str = "/xrpc/chat.bsky.convo.listConvos";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = ListConvos<S>;
    type Response = ListConvosResponse;
}

fn _default_limit() -> Option<i64> {
    Some(50i64)
}

pub mod list_convos_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct ListConvosBuilder<St: list_convos_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<S>, Option<i64>, Option<S>, Option<S>, Option<S>),
    _type: PhantomData<fn() -> S>,
}

impl ListConvos<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ListConvosBuilder<list_convos_state::Empty, DefaultStr> {
        ListConvosBuilder::new()
    }
}

impl<S: BosStr> ListConvos<S> {
    /// Create a new builder for this type
    pub fn builder() -> ListConvosBuilder<list_convos_state::Empty, S> {
        ListConvosBuilder::builder()
    }
}

impl ListConvosBuilder<list_convos_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ListConvosBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ListConvosBuilder<list_convos_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ListConvosBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: list_convos_state::State, S: BosStr> ListConvosBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: list_convos_state::State, S: BosStr> ListConvosBuilder<St, S> {
    /// Set the `kind` field (optional)
    pub fn kind(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `kind` field to an Option value (optional)
    pub fn maybe_kind(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: list_convos_state::State, S: BosStr> ListConvosBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: list_convos_state::State, S: BosStr> ListConvosBuilder<St, S> {
    /// Set the `lockStatus` field (optional)
    pub fn lock_status(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `lockStatus` field to an Option value (optional)
    pub fn maybe_lock_status(mut self, value: Option<S>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St: list_convos_state::State, S: BosStr> ListConvosBuilder<St, S> {
    /// Set the `readState` field (optional)
    pub fn read_state(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `readState` field to an Option value (optional)
    pub fn maybe_read_state(mut self, value: Option<S>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: list_convos_state::State, S: BosStr> ListConvosBuilder<St, S> {
    /// Set the `status` field (optional)
    pub fn status(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `status` field to an Option value (optional)
    pub fn maybe_status(mut self, value: Option<S>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St, S: BosStr> ListConvosBuilder<St, S>
where
    St: list_convos_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> ListConvos<S> {
        ListConvos {
            cursor: self._fields.0,
            kind: self._fields.1,
            limit: self._fields.2,
            lock_status: self._fields.3,
            read_state: self._fields.4,
            status: self._fields.5,
        }
    }
}