// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: chat.bsky.convo.unmuteConvo
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::chat_bsky::convo::ConvoView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct UnmuteConvo<S: BosStr = DefaultStr> {
    pub convo_id: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct UnmuteConvoOutput<S: BosStr = DefaultStr> {
    pub convo: ConvoView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Response type for chat.bsky.convo.unmuteConvo
pub struct UnmuteConvoResponse;
impl jacquard_common::xrpc::XrpcResp for UnmuteConvoResponse {
    const NSID: &'static str = "chat.bsky.convo.unmuteConvo";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = UnmuteConvoOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for UnmuteConvo<S> {
    const NSID: &'static str = "chat.bsky.convo.unmuteConvo";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = UnmuteConvoResponse;
}

/// Endpoint type for chat.bsky.convo.unmuteConvo
pub struct UnmuteConvoRequest;
impl jacquard_common::xrpc::XrpcEndpoint for UnmuteConvoRequest {
    const PATH: &'static str = "/xrpc/chat.bsky.convo.unmuteConvo";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = UnmuteConvo<S>;
    type Response = UnmuteConvoResponse;
}