// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: tools.ozone.communication.updateTemplate
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Did, Language};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};
use crate::tools_ozone::communication::TemplateView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct UpdateTemplate<S: BosStr = DefaultStr> {
    ///Content of the template, markdown supported, can contain variable placeholders.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_markdown: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    ///ID of the template to be updated.
    pub id: S,
    ///Message language.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<Language>,
    ///Name of the template.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<S>,
    ///Subject of the message, used in emails.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<S>,
    ///DID of the user who is updating the template.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Did<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct UpdateTemplateOutput<S: BosStr = DefaultStr> {
    #[serde(flatten)]
    pub value: TemplateView<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum UpdateTemplateError {
    #[serde(rename = "DuplicateTemplateName")]
    DuplicateTemplateName(Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other { error: SmolStr, message: Option<SmolStr> },
}

impl core::fmt::Display for UpdateTemplateError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::DuplicateTemplateName(msg) => {
                write!(f, "DuplicateTemplateName")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/// Response type for tools.ozone.communication.updateTemplate
pub struct UpdateTemplateResponse;
impl jacquard_common::xrpc::XrpcResp for UpdateTemplateResponse {
    const NSID: &'static str = "tools.ozone.communication.updateTemplate";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = UpdateTemplateOutput<S>;
    type Err = UpdateTemplateError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for UpdateTemplate<S> {
    const NSID: &'static str = "tools.ozone.communication.updateTemplate";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = UpdateTemplateResponse;
}

/// Endpoint type for tools.ozone.communication.updateTemplate
pub struct UpdateTemplateRequest;
impl jacquard_common::xrpc::XrpcEndpoint for UpdateTemplateRequest {
    const PATH: &'static str = "/xrpc/tools.ozone.communication.updateTemplate";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = UpdateTemplate<S>;
    type Response = UpdateTemplateResponse;
}