// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `tools.ozone.team` namespace.
pub mod add_member;
pub mod defs;
pub mod delete_member;
pub mod list_members;
pub mod update_member;
