// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: tools.ozone.signature.findRelatedAccounts
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Did;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::com_atproto::admin::AccountView;
use crate::tools_ozone::signature::SigDetail;
use crate::tools_ozone::signature::find_related_accounts;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct FindRelatedAccounts<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub did: Did<S>,
    /// Defaults to `50`. Min: 1. Max: 100.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct FindRelatedAccountsOutput<S: BosStr = DefaultStr> {
    pub accounts: Vec<find_related_accounts::RelatedAccount<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct RelatedAccount<S: BosStr = DefaultStr> {
    pub account: AccountView<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub similarities: Option<Vec<SigDetail<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `tools.ozone.signature.findRelatedAccounts` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `FindRelatedAccountsOutput<S>` for this endpoint.*/
pub struct FindRelatedAccountsResponse;
impl jacquard_common::xrpc::XrpcResp for FindRelatedAccountsResponse {
    const NSID: &'static str = "tools.ozone.signature.findRelatedAccounts";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = FindRelatedAccountsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for FindRelatedAccounts<S> {
    const NSID: &'static str = "tools.ozone.signature.findRelatedAccounts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = FindRelatedAccountsResponse;
}

/** Endpoint marker for the `tools.ozone.signature.findRelatedAccounts` query.

Path: `/xrpc/tools.ozone.signature.findRelatedAccounts`. The request payload type is `FindRelatedAccounts<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct FindRelatedAccountsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for FindRelatedAccountsRequest {
    const PATH: &'static str = "/xrpc/tools.ozone.signature.findRelatedAccounts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = FindRelatedAccounts<S>;
    type Response = FindRelatedAccountsResponse;
}

impl<S: BosStr> LexiconSchema for RelatedAccount<S> {
    fn nsid() -> &'static str {
        "tools.ozone.signature.findRelatedAccounts"
    }
    fn def_name() -> &'static str {
        "relatedAccount"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_tools_ozone_signature_findRelatedAccounts()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

fn _default_limit() -> Option<i64> {
    Some(50i64)
}

pub mod find_related_accounts_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDid<St> {}
    impl<St: State> State for SetDid<St> {
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type.
pub struct FindRelatedAccountsBuilder<
    St: find_related_accounts_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<Did<S>>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl FindRelatedAccounts<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> FindRelatedAccountsBuilder<
        find_related_accounts_state::Empty,
        DefaultStr,
    > {
        FindRelatedAccountsBuilder::new()
    }
}

impl<S: BosStr> FindRelatedAccounts<S> {
    /// Create a new builder for this type
    pub fn builder() -> FindRelatedAccountsBuilder<
        find_related_accounts_state::Empty,
        S,
    > {
        FindRelatedAccountsBuilder::builder()
    }
}

impl FindRelatedAccountsBuilder<find_related_accounts_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        FindRelatedAccountsBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> FindRelatedAccountsBuilder<find_related_accounts_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        FindRelatedAccountsBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<
    St: find_related_accounts_state::State,
    S: BosStr,
> FindRelatedAccountsBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St, S: BosStr> FindRelatedAccountsBuilder<St, S>
where
    St: find_related_accounts_state::State,
    St::Did: find_related_accounts_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<S>>,
    ) -> FindRelatedAccountsBuilder<find_related_accounts_state::SetDid<St>, S> {
        self._fields.1 = Option::Some(value.into());
        FindRelatedAccountsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<
    St: find_related_accounts_state::State,
    S: BosStr,
> FindRelatedAccountsBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> FindRelatedAccountsBuilder<St, S>
where
    St: find_related_accounts_state::State,
    St::Did: find_related_accounts_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> FindRelatedAccounts<S> {
        FindRelatedAccounts {
            cursor: self._fields.0,
            did: self._fields.1.unwrap(),
            limit: self._fields.2,
        }
    }
}

pub mod related_account_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Account;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Account = Unset;
    }
    ///State transition - sets the `account` field to Set
    pub struct SetAccount<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetAccount<St> {}
    impl<St: State> State for SetAccount<St> {
        type Account = Set<members::account>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `account` field
        pub struct account(());
    }
}

/// Builder for constructing an instance of this type.
pub struct RelatedAccountBuilder<
    St: related_account_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<AccountView<S>>, Option<Vec<SigDetail<S>>>),
    _type: PhantomData<fn() -> S>,
}

impl RelatedAccount<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> RelatedAccountBuilder<related_account_state::Empty, DefaultStr> {
        RelatedAccountBuilder::new()
    }
}

impl<S: BosStr> RelatedAccount<S> {
    /// Create a new builder for this type
    pub fn builder() -> RelatedAccountBuilder<related_account_state::Empty, S> {
        RelatedAccountBuilder::builder()
    }
}

impl RelatedAccountBuilder<related_account_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        RelatedAccountBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> RelatedAccountBuilder<related_account_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        RelatedAccountBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RelatedAccountBuilder<St, S>
where
    St: related_account_state::State,
    St::Account: related_account_state::IsUnset,
{
    /// Set the `account` field (required)
    pub fn account(
        mut self,
        value: impl Into<AccountView<S>>,
    ) -> RelatedAccountBuilder<related_account_state::SetAccount<St>, S> {
        self._fields.0 = Option::Some(value.into());
        RelatedAccountBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: related_account_state::State, S: BosStr> RelatedAccountBuilder<St, S> {
    /// Set the `similarities` field (optional)
    pub fn similarities(mut self, value: impl Into<Option<Vec<SigDetail<S>>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `similarities` field to an Option value (optional)
    pub fn maybe_similarities(mut self, value: Option<Vec<SigDetail<S>>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> RelatedAccountBuilder<St, S>
where
    St: related_account_state::State,
    St::Account: related_account_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> RelatedAccount<S> {
        RelatedAccount {
            account: self._fields.0.unwrap(),
            similarities: self._fields.1,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> RelatedAccount<S> {
        RelatedAccount {
            account: self._fields.0.unwrap(),
            similarities: self._fields.1,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_tools_ozone_signature_findRelatedAccounts() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("tools.ozone.signature.findRelatedAccounts"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::XrpcQuery(LexXrpcQuery {
                    parameters: Some(
                        LexXrpcQueryParameter::Params(LexXrpcParameters {
                            required: Some(vec![SmolStr::new_static("did")]),
                            properties: {
                                #[allow(unused_mut)]
                                let mut map = BTreeMap::new();
                                map.insert(
                                    SmolStr::new_static("cursor"),
                                    LexXrpcParametersProperty::String(LexString {
                                        ..Default::default()
                                    }),
                                );
                                map.insert(
                                    SmolStr::new_static("did"),
                                    LexXrpcParametersProperty::String(LexString {
                                        format: Some(LexStringFormat::Did),
                                        ..Default::default()
                                    }),
                                );
                                map.insert(
                                    SmolStr::new_static("limit"),
                                    LexXrpcParametersProperty::Integer(LexInteger {
                                        ..Default::default()
                                    }),
                                );
                                map
                            },
                            ..Default::default()
                        }),
                    ),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("relatedAccount"),
                LexUserType::Object(LexObject {
                    required: Some(vec![SmolStr::new_static("account")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("account"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static(
                                    "com.atproto.admin.defs#accountView",
                                ),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("similarities"),
                            LexObjectProperty::Array(LexArray {
                                items: LexArrayItem::Ref(LexRef {
                                    r#ref: CowStr::new_static(
                                        "tools.ozone.signature.defs#sigDetail",
                                    ),
                                    ..Default::default()
                                }),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}