// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: tools.ozone.signature.searchAccounts
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::com_atproto::admin::AccountView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct SearchAccounts<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    ///Defaults to `50`. Min: 1. Max: 100.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    pub values: Vec<S>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct SearchAccountsOutput<S: BosStr = DefaultStr> {
    pub accounts: Vec<AccountView<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Response type for tools.ozone.signature.searchAccounts
pub struct SearchAccountsResponse;
impl jacquard_common::xrpc::XrpcResp for SearchAccountsResponse {
    const NSID: &'static str = "tools.ozone.signature.searchAccounts";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = SearchAccountsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for SearchAccounts<S> {
    const NSID: &'static str = "tools.ozone.signature.searchAccounts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = SearchAccountsResponse;
}

/// Endpoint type for tools.ozone.signature.searchAccounts
pub struct SearchAccountsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for SearchAccountsRequest {
    const PATH: &'static str = "/xrpc/tools.ozone.signature.searchAccounts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = SearchAccounts<S>;
    type Response = SearchAccountsResponse;
}

fn _default_limit() -> Option<i64> {
    Some(50i64)
}

pub mod search_accounts_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Values;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Values = Unset;
    }
    ///State transition - sets the `values` field to Set
    pub struct SetValues<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetValues<St> {}
    impl<St: State> State for SetValues<St> {
        type Values = Set<members::values>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `values` field
        pub struct values(());
    }
}

/// Builder for constructing an instance of this type.
pub struct SearchAccountsBuilder<S: BosStr, St: search_accounts_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>, Option<Vec<S>>),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> SearchAccounts<S> {
    /// Create a new builder for this type.
    pub fn new() -> SearchAccountsBuilder<S, search_accounts_state::Empty> {
        SearchAccountsBuilder::new()
    }
}

impl<S: BosStr> SearchAccountsBuilder<S, search_accounts_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        SearchAccountsBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: search_accounts_state::State> SearchAccountsBuilder<S, St> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<S: BosStr, St: search_accounts_state::State> SearchAccountsBuilder<S, St> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<S: BosStr, St> SearchAccountsBuilder<S, St>
where
    St: search_accounts_state::State,
    St::Values: search_accounts_state::IsUnset,
{
    /// Set the `values` field (required)
    pub fn values(
        mut self,
        value: impl Into<Vec<S>>,
    ) -> SearchAccountsBuilder<S, search_accounts_state::SetValues<St>> {
        self._fields.2 = Option::Some(value.into());
        SearchAccountsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> SearchAccountsBuilder<S, St>
where
    St: search_accounts_state::State,
    St::Values: search_accounts_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> SearchAccounts<S> {
        SearchAccounts {
            cursor: self._fields.0,
            limit: self._fields.1,
            values: self._fields.2.unwrap(),
        }
    }
}