// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `com.atproto.repo.strongRef` namespace.
//!A URI with a content-hash fingerprint.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MainData {
    pub cid: atrium_api::types::string::Cid,
    pub uri: String,
}
pub type Main = atrium_api::types::Object<MainData>;
