// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: tools.ozone.moderation.getRecords
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};
use crate::tools_ozone::moderation::RecordViewDetail;
use crate::tools_ozone::moderation::RecordViewNotFound;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetRecords<S: BosStr = DefaultStr> {
    pub uris: Vec<AtUri<S>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetRecordsOutput<S: BosStr = DefaultStr> {
    pub records: Vec<GetRecordsOutputRecordsItem<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[open_union]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(tag = "$type", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub enum GetRecordsOutputRecordsItem<S: BosStr = DefaultStr> {
    #[serde(rename = "tools.ozone.moderation.defs#recordViewDetail")]
    RecordViewDetail(Box<RecordViewDetail<S>>),
    #[serde(rename = "tools.ozone.moderation.defs#recordViewNotFound")]
    RecordViewNotFound(Box<RecordViewNotFound<S>>),
}

/// Response type for tools.ozone.moderation.getRecords
pub struct GetRecordsResponse;
impl jacquard_common::xrpc::XrpcResp for GetRecordsResponse {
    const NSID: &'static str = "tools.ozone.moderation.getRecords";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetRecordsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetRecords<S> {
    const NSID: &'static str = "tools.ozone.moderation.getRecords";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetRecordsResponse;
}

/// Endpoint type for tools.ozone.moderation.getRecords
pub struct GetRecordsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetRecordsRequest {
    const PATH: &'static str = "/xrpc/tools.ozone.moderation.getRecords";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetRecords<S>;
    type Response = GetRecordsResponse;
}

pub mod get_records_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uris;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uris = Unset;
    }
    ///State transition - sets the `uris` field to Set
    pub struct SetUris<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUris<St> {}
    impl<St: State> State for SetUris<St> {
        type Uris = Set<members::uris>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uris` field
        pub struct uris(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetRecordsBuilder<S: BosStr, St: get_records_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Vec<AtUri<S>>>,),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> GetRecords<S> {
    /// Create a new builder for this type.
    pub fn new() -> GetRecordsBuilder<S, get_records_state::Empty> {
        GetRecordsBuilder::new()
    }
}

impl<S: BosStr> GetRecordsBuilder<S, get_records_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        GetRecordsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> GetRecordsBuilder<S, St>
where
    St: get_records_state::State,
    St::Uris: get_records_state::IsUnset,
{
    /// Set the `uris` field (required)
    pub fn uris(
        mut self,
        value: impl Into<Vec<AtUri<S>>>,
    ) -> GetRecordsBuilder<S, get_records_state::SetUris<St>> {
        self._fields.0 = Option::Some(value.into());
        GetRecordsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> GetRecordsBuilder<S, St>
where
    St: get_records_state::State,
    St::Uris: get_records_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetRecords<S> {
        GetRecords {
            uris: self._fields.0.unwrap(),
        }
    }
}