// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: tools.ozone.moderation.getRepos
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Did;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};
use crate::tools_ozone::moderation::RepoViewDetail;
use crate::tools_ozone::moderation::RepoViewNotFound;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetRepos<S: BosStr = DefaultStr> {
    pub dids: Vec<Did<S>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetReposOutput<S: BosStr = DefaultStr> {
    pub repos: Vec<GetReposOutputReposItem<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[open_union]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(tag = "$type", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub enum GetReposOutputReposItem<S: BosStr = DefaultStr> {
    #[serde(rename = "tools.ozone.moderation.defs#repoViewDetail")]
    RepoViewDetail(Box<RepoViewDetail<S>>),
    #[serde(rename = "tools.ozone.moderation.defs#repoViewNotFound")]
    RepoViewNotFound(Box<RepoViewNotFound<S>>),
}

/** Response marker for the `tools.ozone.moderation.getRepos` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetReposOutput<S>` for this endpoint.*/
pub struct GetReposResponse;
impl jacquard_common::xrpc::XrpcResp for GetReposResponse {
    const NSID: &'static str = "tools.ozone.moderation.getRepos";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetReposOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetRepos<S> {
    const NSID: &'static str = "tools.ozone.moderation.getRepos";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetReposResponse;
}

/** Endpoint marker for the `tools.ozone.moderation.getRepos` query.

Path: `/xrpc/tools.ozone.moderation.getRepos`. The request payload type is `GetRepos<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetReposRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetReposRequest {
    const PATH: &'static str = "/xrpc/tools.ozone.moderation.getRepos";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetRepos<S>;
    type Response = GetReposResponse;
}

pub mod get_repos_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Dids;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Dids = Unset;
    }
    ///State transition - sets the `dids` field to Set
    pub struct SetDids<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDids<St> {}
    impl<St: State> State for SetDids<St> {
        type Dids = Set<members::dids>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `dids` field
        pub struct dids(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetReposBuilder<St: get_repos_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Vec<Did<S>>>,),
    _type: PhantomData<fn() -> S>,
}

impl GetRepos<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetReposBuilder<get_repos_state::Empty, DefaultStr> {
        GetReposBuilder::new()
    }
}

impl<S: BosStr> GetRepos<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetReposBuilder<get_repos_state::Empty, S> {
        GetReposBuilder::builder()
    }
}

impl GetReposBuilder<get_repos_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetReposBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetReposBuilder<get_repos_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetReposBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetReposBuilder<St, S>
where
    St: get_repos_state::State,
    St::Dids: get_repos_state::IsUnset,
{
    /// Set the `dids` field (required)
    pub fn dids(
        mut self,
        value: impl Into<Vec<Did<S>>>,
    ) -> GetReposBuilder<get_repos_state::SetDids<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetReposBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetReposBuilder<St, S>
where
    St: get_repos_state::State,
    St::Dids: get_repos_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetRepos<S> {
        GetRepos {
            dids: self._fields.0.unwrap(),
        }
    }
}