// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: chat.bsky.actor.deleteAccount
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct DeleteAccountOutput<S: BosStr = DefaultStr> {
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// XRPC request marker type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct DeleteAccount;
/// Response type for chat.bsky.actor.deleteAccount
pub struct DeleteAccountResponse;
impl jacquard_common::xrpc::XrpcResp for DeleteAccountResponse {
    const NSID: &'static str = "chat.bsky.actor.deleteAccount";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = DeleteAccountOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl jacquard_common::xrpc::XrpcRequest for DeleteAccount {
    const NSID: &'static str = "chat.bsky.actor.deleteAccount";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = DeleteAccountResponse;
}

/// Endpoint type for chat.bsky.actor.deleteAccount
pub struct DeleteAccountRequest;
impl jacquard_common::xrpc::XrpcEndpoint for DeleteAccountRequest {
    const PATH: &'static str = "/xrpc/chat.bsky.actor.deleteAccount";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = DeleteAccount;
    type Response = DeleteAccountResponse;
}