// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: chat.bsky.actor.exportAccountData
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::bytes::Bytes;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ExportAccountDataOutput {
    pub body: Bytes,
}

/// XRPC request marker type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct ExportAccountData;
/// Response type for chat.bsky.actor.exportAccountData
pub struct ExportAccountDataResponse;
impl jacquard_common::xrpc::XrpcResp for ExportAccountDataResponse {
    const NSID: &'static str = "chat.bsky.actor.exportAccountData";
    const ENCODING: &'static str = "application/jsonl";
    type Output<S: BosStr> = ExportAccountDataOutput;
    type Err = jacquard_common::xrpc::GenericError;
    fn encode_output<S: BosStr>(
        output: &Self::Output<S>,
    ) -> Result<Vec<u8>, jacquard_common::xrpc::EncodeError>
    where
        Self::Output<S>: Serialize,
    {
        Ok(output.body.to_vec())
    }
    fn decode_output<'de, S>(
        body: &'de [u8],
    ) -> Result<Self::Output<S>, jacquard_common::error::DecodeError>
    where
        S: BosStr + Deserialize<'de>,
        Self::Output<S>: Deserialize<'de>,
    {
        Ok(ExportAccountDataOutput {
            body: jacquard_common::deps::bytes::Bytes::copy_from_slice(body),
        })
    }
}

impl jacquard_common::xrpc::XrpcRequest for ExportAccountData {
    const NSID: &'static str = "chat.bsky.actor.exportAccountData";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ExportAccountDataResponse;
}

/// Endpoint type for chat.bsky.actor.exportAccountData
pub struct ExportAccountDataRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ExportAccountDataRequest {
    const PATH: &'static str = "/xrpc/chat.bsky.actor.exportAccountData";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = ExportAccountData;
    type Response = ExportAccountDataResponse;
}