// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.admin.enableAccountInvites
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Did;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct EnableAccountInvites<S: BosStr = DefaultStr> {
    pub account: Did<S>,
    ///Optional reason for enabled invites.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Response type for com.atproto.admin.enableAccountInvites
pub struct EnableAccountInvitesResponse;
impl jacquard_common::xrpc::XrpcResp for EnableAccountInvitesResponse {
    const NSID: &'static str = "com.atproto.admin.enableAccountInvites";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ();
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for EnableAccountInvites<S> {
    const NSID: &'static str = "com.atproto.admin.enableAccountInvites";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = EnableAccountInvitesResponse;
}

/// Endpoint type for com.atproto.admin.enableAccountInvites
pub struct EnableAccountInvitesRequest;
impl jacquard_common::xrpc::XrpcEndpoint for EnableAccountInvitesRequest {
    const PATH: &'static str = "/xrpc/com.atproto.admin.enableAccountInvites";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = EnableAccountInvites<S>;
    type Response = EnableAccountInvitesResponse;
}

pub mod enable_account_invites_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Account;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Account = Unset;
    }
    ///State transition - sets the `account` field to Set
    pub struct SetAccount<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetAccount<St> {}
    impl<St: State> State for SetAccount<St> {
        type Account = Set<members::account>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `account` field
        pub struct account(());
    }
}

/// Builder for constructing an instance of this type.
pub struct EnableAccountInvitesBuilder<
    S: BosStr,
    St: enable_account_invites_state::State,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Did<S>>, Option<S>),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> EnableAccountInvites<S> {
    /// Create a new builder for this type.
    pub fn new() -> EnableAccountInvitesBuilder<S, enable_account_invites_state::Empty> {
        EnableAccountInvitesBuilder::new()
    }
}

impl<S: BosStr> EnableAccountInvitesBuilder<S, enable_account_invites_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        EnableAccountInvitesBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> EnableAccountInvitesBuilder<S, St>
where
    St: enable_account_invites_state::State,
    St::Account: enable_account_invites_state::IsUnset,
{
    /// Set the `account` field (required)
    pub fn account(
        mut self,
        value: impl Into<Did<S>>,
    ) -> EnableAccountInvitesBuilder<S, enable_account_invites_state::SetAccount<St>> {
        self._fields.0 = Option::Some(value.into());
        EnableAccountInvitesBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<
    S: BosStr,
    St: enable_account_invites_state::State,
> EnableAccountInvitesBuilder<S, St> {
    /// Set the `note` field (optional)
    pub fn note(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `note` field to an Option value (optional)
    pub fn maybe_note(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<S: BosStr, St> EnableAccountInvitesBuilder<S, St>
where
    St: enable_account_invites_state::State,
    St::Account: enable_account_invites_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> EnableAccountInvites<S> {
        EnableAccountInvites {
            account: self._fields.0.unwrap(),
            note: self._fields.1,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> EnableAccountInvites<S> {
        EnableAccountInvites {
            account: self._fields.0.unwrap(),
            note: self._fields.1,
            extra_data: Some(extra_data),
        }
    }
}